# Generated by Django 4.2.4 on 2023-08-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(null=True, upload_to='', verbose_name='изображение (превью)'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views_number',
            field=models.IntegerField(null=True),
        ),
    ]
