# Generated by Django 4.2.4 on 2023-08-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_comments_alter_blog_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='slug'),
        ),
    ]
