# Generated by Django 4.2.4 on 2023-08-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='new',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
