# Generated by Django 4.2.4 on 2023-08-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='User_Contact',
        ),
    ]
