# Generated by Django 4.2.4 on 2023-08-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_suppliers_supplier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Contact',
            new_name='UserContact',
        ),
    ]
