# Generated by Django 4.2.4 on 2023-08-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_category_title_alter_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=100, unique=True, verbose_name='наименование'), max_length=255, verbose_name='slug'),
        ),
    ]
