# Generated by Django 4.2.4 on 2023-09-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_avatar_alter_user_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='title',
            field=models.CharField(max_length=15, unique=True, verbose_name='Country'),
        ),
    ]
